kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: frontend-ingress
  namespace: frontend
  annotations:
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    # cert-manager.io/acme-challenge-type: dns01
spec:
  ingressClassName: nginx
  rules:
    - host: fe.alv.pp.ua
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: 80