# ---- Build Stage ----
FROM node:20-alpine AS build
WORKDIR /app
COPY ../frontend /app
RUN npm install -g @angular/cli
RUN npm install && ng build

#RUN ng build --configuration production
#CMD ["sleep", "1000000"]


FROM nginx:mainline-alpine3.22
#FROM httpd:2.4-alpine
COPY --from=build /app/dist/frontend/browser/ /usr/share/nginx/html

COPY infrastructure/docker/nginx.conf /etc/nginx/conf.d/angular.conf

