# ---- Build Stage ----
FROM eclipse-temurin:8u452-b09-jre-ubi9-minimal AS builder
WORKDIR /app
COPY ../backend /app
RUN /app/mvnw package
ENV SPRING_PROFILES_ACTIVE=prod
CMD ["java", "-jar", "/app/target/application-0.0.1-SNAPSHOT.jar"]

# # ---- Run Stage ----
# FROM eclipse-temurin:24-jre
# WORKDIR /app
# COPY --from=build /app/target/application-0.0.1-SNAPSHOT.jar /app/app.jar
# EXPOSE 8080
#ENV SPRING_PROFILES_ACTIVE=prod
# ENTRYPOINT ["java", "-jar", "/app/app.jar"]
