FROM eclipse-temurin:24-jdk-alpine AS builder
WORKDIR /app
COPY ../backend /app
RUN /app/mvnw package


FROM eclipse-temurin:24-jre-alpine
WORKDIR /app
COPY --from=builder /app/target/application-0.0.1-SNAPSHOT.jar /app/target/application-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/app/target/application-0.0.1-SNAPSHOT.jar"]
