FROM node:20-alpine AS build
WORKDIR /app
COPY ../frontend /app
RUN npm install -g @angular/cli
RUN npm install && ng build

FROM nginx:mainline-alpine3.22
COPY --from=build /app/dist/frontend/browser/ /usr/share/nginx/html
COPY infrastructure/docker/nginx.conf /etc/nginx/conf.d/angular.conf